name: wander_pal
description: Connect with like-minded travelers
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  google_sign_in: ^6.1.0
  graphql_flutter: ^5.1.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_facebook_auth: ^5.0.11
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0
  build_runner: ^2.4.4
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages