// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDPsWjb92MW1bgkCaLq7fpno-r5G4f1l10",
    appId: "1:579543416549:web:c864f816f59ec93768de0c",
    messagingSenderId: "579543416549",
    projectId: "wander-pal",
    authDomain: "wander-pal.firebaseapp.com",
    storageBucket: "wander-pal.appspot.com",
    measurementId: "G-HWQ2ZEYZ8T",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBNqpYbtTtOsnLXJzxQ0h2mmiEPU2Gkf1Q",
    appId: "1:579543416549:android:039d16c225e21c9c68de0c",
    messagingSenderId: "579543416549",
    projectId: "wander-pal",
    storageBucket: "wander-pal.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCS6jk2H9GGzYFv2H0uwlo5HHZV58kyrJ4",
    appId: "1:579543416549:ios:7276b8b6b3e2ab4968de0c",
    messagingSenderId: "579543416549",
    projectId: "wander-pal",
    storageBucket: "wander-pal.appspot.com",
    iosClientId: "579543416549-s472o2gl8fnghej1ljout6iuoqju3he5.apps.googleusercontent.com",
    iosBundleId: "com.example.wanderPal",
  );
}